savido_webinterface/presets/urls.py
from django.conf.urls import url

from . import views

app_name= 'presets'

# create url patterns to open application with browser
urlpatterns = [  
    url(r'^player$', views.PlayerView.as_view(), name='player'),
    url(r'$', views.IndexView.as_view(), name='index'),
]

savido_webinterface/savido_webinterface/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^presets/', include('presets.urls')),
    url(r'^m_presets/', include('mobile_presets.urls')),
]

savido_webinterface/presets/models.py
from __future__ import unicode_literals

from django.db import models


MAX_LENGTH=32
MAX_LENGTH_URL = 100

# create database tables with parameters

class OutputFormat(models.Model):
        name = models.CharField(unique=True, max_length=MAX_LENGTH)
    
            
class Object(models.Model):
    name = models.CharField(unique=True, max_length=MAX_LENGTH)
    objectType = models.CharField(unique=False, max_length=MAX_LENGTH)
    color = models.CharField(null=True, max_length=MAX_LENGTH)
    # get all audioobjects from object     
    def getObject(self, objectType):
        if objectType=="Switchgroup":
                return {'elements': self.getListOfAudioObj(),
                'type':'switchGroup'
                        }
        else:
            audioObj = AudioObject.objects.get(obj=self)
            return audioObj.getAODict()

    # get all audioobject for object/switchgroups with foreign key (obj) 
    def getListOfAudioObj(self): 
        if self.objectType == "Switchgroup":
            aoName = [audioobject.name for audioobject in AudioObject.objects.filter(obj=self).order_by('name')]      
            aoDict = [audioobject.getAODict() for audioobject in AudioObject.objects.filter(obj=self).order_by('name')] 
            # create dict from audioobjects and parameters
            listOfAO = dict(zip(aoName, aoDict))
            return listOfAO

        
class AudioObject(models.Model):
    name = models.CharField(unique=True, max_length=MAX_LENGTH)
    url = models.CharField(null = True, max_length= MAX_LENGTH_URL)
    channel = models.IntegerField(null=True, default=0)
    timeRangeStart = models.IntegerField(null=True, default=0)
    timeRangeStop = models.IntegerField(null=True, default=0)
    obj = models.ForeignKey(Object, on_delete=models.CASCADE)
    color = models.CharField(null=True, max_length=MAX_LENGTH)
    # create dict with audioobject and parameters
    def getAODict(self):
            return {'type': 'audioObject',
                    'source': { 'url' :self.url,
                               'channel' : self.channel,
                               },
                    'timeRange':{'start':self.timeRangeStart, 'stop':self.timeRangeStop},
                    'parameters': self.getListOfParam()
                    }
    # get all parameters for audioobject with foreign key (audioobject)                
    def getListOfParam(self):
        paramName = [parameter.name for parameter in Parameter.objects.filter(audioobject=self).order_by('name')]
        paramPV = [parameter.getListOfParameterValue() for parameter in Parameter.objects.filter(audioobject=self).order_by('name')]
        # create dict with parameters and pv
        listOfParam = dict(zip(paramName, paramPV))
        return listOfParam
        
class Parameter(models.Model):
    name= models.CharField(null = True, max_length= MAX_LENGTH)
    audioobject = models.ForeignKey(AudioObject, on_delete=models.CASCADE)
    # get all values for parameter with foreign key (parameter)
    def getListOfParameterValue(self):
        pvName = [parametervalue.name for parametervalue in ParameterValue.objects.filter(parameter=self).order_by('name')]
        pvValue = [parametervalue.getValue() for parametervalue in ParameterValue.objects.filter(parameter=self).order_by('name')]
        # create dict with parametervalues
        listOfPV=dict(zip(pvName, pvValue))
        return listOfPV
                

class ParameterValue(models.Model):
    name = models.CharField(null = True, max_length= MAX_LENGTH)
    value=models.FloatField(null = True, default=0)
    valuex=models.FloatField(null = True, default=0)
    valuey=models.FloatField(null = True, default=0)
    valuez=models.FloatField(null = True, default=0)
    parameter = models.ForeignKey(Parameter, on_delete=models.CASCADE)
    forAll = models.BooleanField(default = False);

    # get all values for parameter with foreign key (parameter)        
    def getValue(self):
        value=self.value
        if self.parameter.name =='Pos':
            value=[self.valuex, self.valuey, self.valuez]
        return value
        

savido_webinterface/presets/views.py
from django.shortcuts import render, get_object_or_404
from django.utils.datastructures import MultiValueDictKeyError
from django.template import RequestContext
from django.views import generic
from django.core import serializers

from .models import Object, OutputFormat, AudioObject, Parameter, ParameterValue
from .DBProcessor import dbProcessor

import json
import os.path

db = dbProcessor()

# Create all views
class IndexView(generic.TemplateView):
    template_name= 'presets/index.html'
    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        
        # set context with database entries for templates
        context['objList'] = Object.objects.all()
        
        data=serializers.serialize("json", OutputFormat.objects.all())
        context['outputListJS']=data        
        
        data= serializers.serialize("json", Object.objects.all())
        context['objListJS']=data
        
        data=serializers.serialize("json", AudioObject.objects.all())
        context['aoListJS']=data
        
        data=serializers.serialize("json", Parameter.objects.all())
        context['paramListJS']=data
        
        data=serializers.serialize("json", ParameterValue.objects.all())
        context['pVListJS']=data
       
        return context
        
    def get(self, request, *args, **kwargs):
        x = request.GET
        context = self.get_context_data(params=x)

        # all interactions with production tool                                                
        if 'action' in x:
            if x['action'] == "writeSG":
                db.writeSG(x)
                    
            if x['action'] == "writeAO":
                db.writeAO(x)
                
            if x['action'] == "delete":                                
                db.deleteObject(x)
                
            if x['action'] == "addOutputFormat":
                db.writeOutputFormat(x);
    
            if x['action'] == "saveScene":
                db.refreshJSON(x)

        return super(generic.TemplateView, self).render_to_response(context)
        
     
        
class PlayerView(generic.TemplateView):
    template_name='presets/player.html'
    

savido_webinterface/presets/templates/presets/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <!-- set title and icon for head -->
    <title>Presets</title>
    <link rel="shortcut icon" type="image/x-icon" href="presets/img/irt.ico">
    <!-- load css file -->
    <link rel="stylesheet" type="text/css" href="{% static 'presets/css/style.css' %}" />	
  </head>
  <body>
    <!-- divide template in heading, sidebar and controll view--> 
	<h1>Create an object-based audioscene</h1>
	<section>
		{% block objects %}
		{%endblock%}
	</section>

	<aside>
		{% block video %}
		{%endblock%}
	</aside>

  </body>
</html>

savido_webinterface/presets/templates/presets/index.html
{% extends 'presets/base.html' %}

<!-- Sidebar with list of DB entries -->
{% block objects %}
  <h2>Audioobjects</h2>
	{% for obj in objList %}
	<details>
        <!-- Object names as visible headings for the <details> elements -->
        <summary>{{obj.name}}</summary>

        <!-- Object Details -->	
        <!-- Delete and edit Buttons for every Object -->
	    <form method='get' action=''>
            <input type='hidden' name='Object' value={{obj.id}}>
            <input type="button" value="Edit" onclick="editObject({{obj.id}})" />
            <input type='button' value="Delete" onclick="deleteObjSidebar({{obj.id}})"/>
	    </form>

        <!-- List of object parameter -->
	    <p><li><b>Objecttype:</b> {{obj.objectType}}</li></p>	
        <p><li><b>Color:</b> {{obj.color}}</li></p>
        
        <!-- Differentiate list of parameters with objecttypes -->
        <!-- Objecttype is audioobject -->
        {% if obj.objectType == "Audioobject" %}
	        <p>
	        {%for audioobject in obj.audioobject_set.all%}
	            <li><b>URL:</b> {{audioobject.url}}</li>
	            <li><b>Channel:</b>{{audioobject.channel}}</li>
                <li><b>TimeRange:</b>
                  <ul> <li>Start: {{audioobject.timeRangeStart}}</li> 
                       <li>Stop: {{audioobject.timeRangeStop}}</li></ul>

             	
	            <li><b>Parameter:</b>
		        <ul>
		        {% for parameter in audioobject.parameter_set.all %}		  
		
			        <li><b>{{parameter.name}}:</b></li>
			        <ul>
			        {%for parameter_value in parameter.parametervalue_set.all%}
				             					
				        {%if parameter.name == "Pos" %}
					        <li>{{parameter_value.name}}: X: {{parameter_value.valuex}} Y: {{parameter_value.valuey}} Z: {{parameter_value.valuez}}</li>
				        {%else%}
					        <li>{{parameter_value.name}}: {{parameter_value.value}}</li>
				        {%endif%}     
			        {%endfor%}

			        </ul>
		        {%endfor%}
		        </ul>	
            {%endfor%}
	        </p>
	    {%endif%}

        <!-- Objecttype is switchgroup -->
	    {%if obj.objectType == "Switchgroup" %}
	    <p>
	    <li><b>Element:</b></li>
		    <ul>
		    {%for audioobject in obj.audioobject_set.all%}
			    <li><b>{{audioobject.name}}:</b></li>
			    <ul>
			    <li><b>Color:</b> {{audioobject.color}}</li>
			    <li><b>URL:</b> {{audioobject.url}}</li>
			    <li><b>Channel:</b> {{audioobject.channel}}</li>
          <li><b>TimeRange:</b>
              <ul> <li>Start: {{audioobject.timeRangeStart}}</li> 
              <li>Stop: {{audioobject.timeRangeStop}}</li></ul>
          <li>
		
	         <li><b>Parameter:</b></li>
		        <ul>
		        
		        {% for parameter in audioobject.parameter_set.all %}
				        <li><b>{{parameter.name}}</b></li>
				        <ul>
					        {%for parameter_value in parameter.parametervalue_set.all%}
							        {%if parameter.name == "Pos" %}
								        <li><b>{{parameter_value.name}}</b>: X: {{parameter_value.valuex}} Y: {{parameter_value.valuey}} Z: {{parameter_value.valuez}}</li>
							        {%else%}
								        <li>{{parameter_value.name}}: {{parameter_value.value}}</li>
							        {%endif%}				     

					        {%endfor%}
				        </ul>
		        {%endfor%}
		        </ul>
		        </ul>
            {%endfor%} 
		    </ul>
		    </p>
	    {%endif%}
	        
	</details> 
	{%endfor%}

    <!-- Buttons for different actions -->
    <input type='button' value="Add new Object" onclick="addNewObject()">	
    <input type='button' value="Add Output Format" onclick="addOutputFormat()">
    <input type='button' value="Save Scene" onclick="saveScene()">

{% endblock %}

<!-- Add control view with computer graphic -->
{%block video%}
 {% include 'presets/player.html' %}
{%endblock%}

savido_webinterface/presets/templates/presets/player.html
{% load static %}
<!DOCTYPE html>
<html> 

<head>
<meta http-equiv="content-type" content="text/html; charset=ISO-8859-1">


<!-- load external libraries -->
<script type="text/javascript" src="{% static 'presets/js/three.js-master/build/three.min.js' %}"></script>
<script type="text/javascript" src="{% static 'presets/js/jquery-3.2.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'presets/js/dat.gui/build/dat.gui.js' %}"></script>

<!-- load internal javascripts -->
<script type="text/javascript" src="{% static 'presets/js/UIProcessor.js' %}"></script>
<script type="text/javascript" src="{% static 'presets/js/EventHelper.js' %}"></script>
<script type="text/javascript" src="{% static 'presets/js/RequestHelper.js' %}"></script>
<script type="text/javascript" src="{% static 'presets/js/MathHelper.js' %}"></script>
<script type="text/javascript" src="{% static 'presets/js/DBListHelper.js' %}"></script>

<script type="text/javascript">
    
    // load DB entries in different lists
    var objList = {{objListJS|safe}};
    var outputList = {{outputListJS|safe}};
    var aoList = {{aoListJS|safe}};
    var paramList = {{paramListJS|safe}};
    var pVList = {{pVListJS|safe}};

    // set geometry for spheres (Audioobjects) and rings (Switchgroups)    
    var geometryElement = new THREE.RingGeometry(1.2, 1.3, 32);
    var geometryObject = new THREE.SphereGeometry(1, 32, 32);

    var canvas;
    // set scene and camera
    var scene = new THREE.Scene();
    var camera = new THREE.PerspectiveCamera(45, 1 , 1, 500);
    var renderer;

    var radius = 15;
    
    // call on start    
    function webGLStart(){  
      // draw 360 degree scene  
      drawScene();   
       
      // set mouse or keyboard evenlisteners
      document.onkeydown = handleKeyDown;
      canvas.ondblclick = handleDblClick;
      canvas.onclick = handleMouseClick;
      canvas.onmousedown = handleMouseDown;
      document.onmouseup = handleMouseUp;
      document.onmousemove = handleMouseMove;
      /*document.onwheel =  handleMouseWheel;*/ //Click and Drag Objects
    } 

    var audioobject; //create global variable audioobject
    // create arrays for audioobjects and switchgroups
    var objects=[];
    var element=[];

    // rendering function 
    function render() {
      requestAnimationFrame( render ); 
      // render scene for every new camera view         
      renderer.render(scene, camera);
    }

    // draw scene class
	function drawScene(){
        // set canvas from ID
        canvas= document.getElementById("canvas");
        // set renderer with canvas 
        renderer = new THREE.WebGLRenderer({canvas:canvas});

        camera.position.z = 0;
        renderer.setSize(canvas.clientWidth, canvas.clientHeight);
        document.body.appendChild(renderer.domElement); 

        // create sphere with texture from static files as room
        var loader = new THREE.TextureLoader();
        var texture = loader.load ("{% static 'presets/img/studio_editor_audioScene.jpg' %}", function (texture) { 
            var geometrySphere = new THREE.SphereGeometry(radius, 32, 32 );
            var materialSphere = new THREE.MeshBasicMaterial( { map: texture } );
            var sphere = new THREE.Mesh( geometrySphere, materialSphere );
            sphere.material.side = THREE.DoubleSide;
            scene.add(sphere);
            loadScenePosition(alpha, beta); 
        });    

        texture.wrapS = THREE.RepeatWrapping; //Drehen des Textures, damit Kamera bei Start auf Center schaut
        texture.wrapT = THREE.ClampToEdgeWrapping;
        texture.offset.x = -Math.PI/2 / (2*Math.PI);
        texture.wrapS = THREE.RepeatWrapping; 
        texture.repeat.x = - 1;

        // call drawObjects function
        drawObjects();
        // call render function to render visual scene
        render();
	} 

    // draw objects function
    function drawObjects(){
      // find all position from objects
      if (objList!= null){
        for(var i in objList){
          renderer.sortObjects = false;
          for(var n in aoList){
            if(aoList[n].fields.obj == objList[i].pk){
              for (var j in paramList){
                if(paramList[j].fields.audioobject==aoList[n].pk && paramList[j].fields.name=="Pos"){
                  for (var m in pVList){
                    if(pVList[m].fields.parameter==paramList[j].pk){
                      // audioobjects are transparent
		              var materialObject = new THREE.MeshBasicMaterial({transparent: true, opacity: 0.5});
                      // combine geometry and material to build audioobjects    
                      var audioobject = new THREE.Mesh(geometryObject, materialObject);
                      
                      // set position values                          
                      audioobject.position.x=pVList[m].fields.valuex;
                      audioobject.position.y=pVList[m].fields.valuez;
                      audioobject.position.z=pVList[m].fields.valuey;
                      // set color value
  		              audioobject.material.color.setHex(aoList[n].fields.color);
                      
                      // add audioobject to scene  
                      scene.add(audioobject);
                      // add audioobject in list with all audioobject
                      objects.push( audioobject );			

                      // if objecttype is switchgroup than add a ring around the audioobject sphere
                      if (objList[i].fields.objectType == "Switchgroup"){
                        // same as audioobjects
                        var materialElement = new THREE.MeshBasicMaterial({side: THREE.DoubleSide});
                        var sgRing = new THREE.Mesh(geometryElement, materialElement);

                        sgRing.position.x = pVList[m].fields.valuex;
                        sgRing.position.y = pVList[m].fields.valuez;
                        sgRing.position.z = pVList[m].fields.valuey;

                        sgRing.material.color.setHex(objList[i].fields.color);
                        sgRing.material.transparent=true;
                        sgRing.material.opacity = 0.5;

                        scene.add(sgRing); 

                        element.push(sgRing);                   
                      }
                    }
                  }
                }
              }
            }
	      }
        }
      }
    }
	    

		
	function makeAllObjectsTransparent(){
        // make all rings and spheres transparent         
        for (var i in element){
          element[i].material.transparent = true;
        }
        for (var i in objects){
          objects[i].material.transparent = true;
        }

        isObjectSelect = false;
    
	}

    // load new camera view function
	function loadScenePosition(alpha, beta){
        // calculate new camera view with angles
	    scene.position.x=radius*Math.sin(degToRad(alpha))*Math.cos(degToRad(beta));
	    scene.position.z=radius*Math.sin(degToRad(alpha))*Math.sin(degToRad(beta));
	    scene.position.y=radius*Math.cos(degToRad(alpha));  
        // set new camera view
	    camera.lookAt(scene.position);
        // render new camera view
	    renderer.render(scene, camera);
	}
</script>
</head>

<body onload="webGLStart();">
  <!-- set canvas with size -->
  <canvas id="canvas" style="border: none;" width ="900" height="750"></canvas> 
  <!-- Video texture -->
  <!--<video id="video" autoplay loop webkit-playsinline style="display:none">
    <source src="{% static 'presets/videos/sample360.mp4' %}" type='video/mp4; codecs="avc1.42E01E, mp4a.40.2"'>
  </video>-->
</body>

</html>